# Generated by Django 4.0.4 on 2022-05-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Viloyat nomi')),
            ],
            options={
                'verbose_name': 'Viloyati',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('content', models.TextField(blank=True, verbose_name='Kontent')),
                ('built_at', models.DateTimeField(verbose_name='Barpo qilingan vaqti')),
                ('updated_at', models.DateTimeField(verbose_name='Yangilangan vaqti')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Rasm')),
                ('views', models.IntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Joy nomi',
                'verbose_name_plural': 'Joy nomlari',
                'ordering': ['-built_at'],
            },
        ),
    ]
